"""OpenAPI and AsyncAPI builders for app bridge contracts."""

from __future__ import annotations

from typing import Any

from .contracts import BridgeCommandSpec, BridgeFunctionSpec, BridgeParamSpec, BridgeQuerySpec, OdooAppBridgeSpec


def json_schema_for_type(type_name: str) -> dict[str, Any]:
    """Return a small JSON Schema fragment for bridge value types."""
    if type_name == "str":
        return {"type": "string"}
    if type_name == "int":
        return {"type": "integer"}
    if type_name == "float":
        return {"type": "number"}
    if type_name == "bool":
        return {"type": "boolean"}
    if type_name == "date":
        return {"type": "string", "format": "date"}
    if type_name == "datetime":
        return {"type": "string", "format": "date-time"}
    if type_name == "json":
        return {}
    if type_name.startswith("list[") and type_name.endswith("]"):
        return {"type": "array", "items": json_schema_for_type(type_name[5:-1])}
    return {}


def schema_for_params(params: tuple[BridgeParamSpec, ...], *, title: str = "") -> dict[str, Any]:
    properties: dict[str, Any] = {}
    required: list[str] = []
    for param in params:
        schema = json_schema_for_type(param.type)
        if param.notes:
            schema["description"] = param.notes
        if param.example is not None:
            schema["examples"] = [param.example]
        elif param.default is not None:
            schema["default"] = param.default
        properties[param.name] = schema
        if param.required:
            required.append(param.name)
    out: dict[str, Any] = {"type": "object", "properties": properties, "additionalProperties": False}
    if title:
        out["title"] = title
    if required:
        out["required"] = required
    return out


def build_openapi_document(spec: OdooAppBridgeSpec) -> dict[str, Any]:
    """Build OpenAPI 3.1 for generated public endpoints."""
    base_prefix = f"/{spec.app.public_prefix}/{spec.app.slug}".replace("//", "/")
    paths: dict[str, Any] = {}
    components: dict[str, Any] = {
        "headers": {
            "XBridgeRequestId": {
                "description": "Opaque request identifier generated by the app bridge.",
                "schema": {"type": "string"},
            },
            "XBridgeContractDigest": {
                "description": "Digest of the deployed bridge contract.",
                "schema": {"type": "string"},
            },
            "IdempotencyKey": {
                "description": "Idempotency key for repeat-safe commands.",
                "schema": {"type": "string"},
            },
            "XBridgeCSRF": {
                "description": "CSRF token required for session-backed commands when configured.",
                "schema": {"type": "string"},
            },
        },
        "schemas": {
            "EnvelopeError": {
                "type": "object",
                "properties": {
                    "ok": {"type": "boolean", "const": False},
                    "error": {"type": "string"},
                    "details": {},
                    "meta": {"type": "object"},
                },
                "required": ["ok", "error"],
                "additionalProperties": True,
            },
            "MetaEnvelope": {
                "type": "object",
                "properties": {
                    "ok": {"type": "boolean", "const": True},
                    "data": {"type": "object"},
                    "request_id": {"type": "string"},
                },
                "required": ["ok"],
                "additionalProperties": True,
            },
        },
    }

    paths["/health"] = _meta_operation("App health")
    paths["/readiness"] = _meta_operation("Readiness checks")
    paths["/metrics"] = _meta_operation("Operational metrics")
    paths["/security_report"] = _meta_operation("Security release report")
    if spec.security.enable_app_login:
        paths["/auth/login"] = _meta_operation("App-local login")
        paths["/auth/me"] = _meta_operation("Current app-local user")
        paths["/auth/logout"] = _meta_operation("App-local logout")
        paths["/auth/oauth2/providers"] = _meta_operation("OAuth2 provider discovery")
        paths["/auth/oauth2/start"] = _meta_operation("Start OAuth2 PKCE login")
        paths["/auth/oauth2/callback"] = _meta_operation("Complete OAuth2 PKCE login")
        paths["/auth/oauth2/link"] = _meta_operation("Link OAuth2 identity to current app user")
        paths["/auth/oauth2/unlink"] = _meta_operation("Unlink OAuth2 identity from current app user")
    if spec.security.expose_contract_endpoint:
        paths["/contract"] = _meta_operation("Bridge contract")
    if spec.security.expose_openapi_endpoint:
        paths["/openapi"] = _meta_operation("OpenAPI document")
    if spec.security.expose_asyncapi_endpoint:
        paths["/asyncapi"] = _meta_operation("AsyncAPI document")

    for query in spec.queries:
        request_schema = f"Query_{query.name}_Request"
        response_schema = f"Query_{query.name}_Response"
        components["schemas"][request_schema] = _query_request_schema(query)
        components["schemas"][response_schema] = _query_response_schema(query)
        paths[f"/{query.path}"] = _query_operation(query, request_schema, response_schema)

    for command in spec.commands:
        request_schema = f"Command_{command.name}_Request"
        response_schema = f"Command_{command.name}_Response"
        components["schemas"][request_schema] = _command_request_schema(command)
        components["schemas"][response_schema] = _command_response_schema(command)
        paths[f"/{command.path}"] = _command_operation(command, request_schema, response_schema)

    for function in spec.functions:
        request_schema = f"Function_{function.name}_Request"
        response_schema = f"Function_{function.name}_Response"
        components["schemas"][request_schema] = _function_request_schema(function)
        components["schemas"][response_schema] = _function_response_schema(function)
        paths[f"/{function.path}"] = _function_operation(function, request_schema, response_schema)

    return {
        "openapi": "3.1.0",
        "info": {
            "title": f"{spec.app.name} App Bridge API",
            "version": spec.app.version,
            "description": spec.app.description or spec.app.summary,
        },
        "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
        "servers": [{"url": base_prefix}],
        "paths": paths,
        "components": components,
        "x-bridge-contract-digest": spec.contract_digest(),
    }


def build_asyncapi_document(spec: OdooAppBridgeSpec) -> dict[str, Any]:
    """Build AsyncAPI 3.0 for bridge event contracts."""
    channels: dict[str, Any] = {}
    operations: dict[str, Any] = {}
    messages: dict[str, Any] = {}
    schemas: dict[str, Any] = {}
    for event in spec.events:
        data_schema = f"{event.name}_data"
        envelope_schema = f"{event.name}_cloudevent"
        schemas[data_schema] = schema_for_params(event.fields, title=f"{event.name} data")
        schemas[envelope_schema] = {
            "type": "object",
            "properties": {
                "specversion": {"type": "string", "const": "1.0"},
                "id": {"type": "string"},
                "type": {"type": "string", "const": event.cloudevent_type},
                "source": {"type": "string", "default": event.source or f"/odoo/{spec.app.slug}"},
                "subject": {"type": "string", "default": event.name},
                "time": {"type": "string", "format": "date-time"},
                "datacontenttype": {"type": "string", "const": "application/json"},
                "data": {"$ref": f"#/components/schemas/{data_schema}"},
            },
            "required": ["specversion", "id", "type", "source", "time", "data"],
            "additionalProperties": True,
        }
        messages[event.name] = {
            "name": event.name,
            "title": event.summary or event.name,
            "summary": event.summary or event.description or event.name,
            "contentType": "application/cloudevents+json",
            "headers": _event_headers_schema(event.required_headers),
            "payload": {"$ref": f"#/components/schemas/{envelope_schema}"},
            "tags": [{"name": tag} for tag in event.tags],
        }
        channels[event.name] = {
            "address": event.channel,
            "messages": {event.name: {"$ref": f"#/components/messages/{event.name}"}},
            "description": event.description or event.summary or event.name,
        }
        operations[f"{event.direction}_{event.name}"] = {
            "action": "send" if event.direction == "outbound" else "receive",
            "channel": {"$ref": f"#/channels/{event.name}"},
            "messages": [{"$ref": f"#/channels/{event.name}/messages/{event.name}"}],
            "summary": event.summary or event.description or event.name,
        }
    return {
        "asyncapi": "3.0.0",
        "info": {
            "title": f"{spec.app.name} App Bridge Events",
            "version": spec.app.version,
            "description": spec.app.description or spec.app.summary,
        },
        "channels": channels,
        "operations": operations,
        "components": {"messages": messages, "schemas": schemas},
        "x-bridge-contract-digest": spec.contract_digest(),
    }


def _meta_operation(summary: str) -> dict[str, Any]:
    return {
        "post": {
            "summary": summary,
            "responses": {
                "200": _response("Successful response", "MetaEnvelope"),
                "403": _response("Forbidden", "EnvelopeError"),
            },
        }
    }


def _response(description: str, schema_name: str) -> dict[str, Any]:
    return {
        "description": description,
        "headers": {
            "X-Bridge-Request-ID": {"$ref": "#/components/headers/XBridgeRequestId"},
            "X-Bridge-Contract-Digest": {"$ref": "#/components/headers/XBridgeContractDigest"},
        },
        "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
    }


def _query_request_schema(query: BridgeQuerySpec) -> dict[str, Any]:
    filters_schema: dict[str, Any] = {"type": "object", "properties": {}, "additionalProperties": False}
    required_filters: list[str] = []
    for item in query.filters:
        schema = json_schema_for_type(item.type)
        if item.notes:
            schema["description"] = item.notes
        if item.example is not None:
            schema["examples"] = [item.example]
        filters_schema["properties"][item.name] = schema
        if item.required:
            required_filters.append(item.name)
    if required_filters:
        filters_schema["required"] = required_filters
    return {
        "type": "object",
        "properties": {
            "filters": filters_schema,
            "limit": {"type": "integer", "minimum": 1, "maximum": query.max_limit, "default": query.default_limit},
            "offset": {"type": "integer", "minimum": 0, "default": 0},
            "sort": {
                "type": "object",
                "properties": {
                    "field": {"type": "string", "enum": list(query.sortable_fields or query.fields)},
                    "dir": {"type": "string", "enum": ["asc", "desc"], "default": "asc"},
                },
                "additionalProperties": False,
            },
            "context": _context_schema(query.allowed_context_keys),
        },
        "additionalProperties": False,
    }


def _query_response_schema(query: BridgeQuerySpec) -> dict[str, Any]:
    fields = tuple(query.response_map.keys()) if query.response_map else query.fields
    row_schema = {
        "type": "object",
        "properties": {field: _guess_field_schema(field) for field in fields},
        "additionalProperties": False,
    }
    return {
        "type": "object",
        "properties": {
            "ok": {"type": "boolean", "const": True},
            "data": {"type": "array", "items": row_schema},
            "meta": {"type": "object", "additionalProperties": True},
        },
        "required": ["ok", "data", "meta"],
        "additionalProperties": True,
    }


def _command_request_schema(command: BridgeCommandSpec) -> dict[str, Any]:
    max_items = command.max_ids if command.max_ids is not None else None
    return {
        "type": "object",
        "properties": {
            "ids": {"type": "array", "items": {"type": "integer", "minimum": 1}, "maxItems": max_items},
            "params": schema_for_params(command.params, title=f"{command.name} params"),
            "context": _context_schema(command.allowed_context_keys),
        },
        "additionalProperties": False,
    }


def _command_response_schema(command: BridgeCommandSpec) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "ok": {"type": "boolean", "const": True},
            "data": {},
            "meta": {
                "type": "object",
                "properties": {
                    "type": {"type": "string", "const": "command"},
                    "name": {"type": "string", "const": command.name},
                    "path": {"type": "string", "const": command.path},
                    "model": {"type": "string", "const": command.model},
                    "method": {"type": "string", "const": command.method},
                },
                "additionalProperties": True,
            },
        },
        "required": ["ok", "data", "meta"],
        "additionalProperties": True,
    }


def _function_request_schema(function: BridgeFunctionSpec) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "params": schema_for_params(function.params, title=f"{function.name} params"),
            "context": _context_schema(function.allowed_context_keys),
        },
        "additionalProperties": False,
    }


def _function_response_schema(function: BridgeFunctionSpec) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {
            "ok": {"type": "boolean", "const": True},
            "data": {},
            "meta": {
                "type": "object",
                "properties": {
                    "type": {"type": "string", "const": "function"},
                    "name": {"type": "string", "const": function.name},
                    "path": {"type": "string", "const": function.path},
                    "handler": {"type": "string", "const": function.handler},
                },
                "additionalProperties": True,
            },
        },
        "required": ["ok", "data", "meta"],
        "additionalProperties": True,
    }


def _query_operation(query: BridgeQuerySpec, request_schema: str, response_schema: str) -> dict[str, Any]:
    return {
        "post": {
            "summary": query.notes or f"Query {query.name}",
            "tags": list(query.tags or ("queries",)),
            "requestBody": _request_body(request_schema),
            "responses": {
                "200": _response("Successful query", response_schema),
                "400": _response("Bad request", "EnvelopeError"),
                "403": _response("Forbidden", "EnvelopeError"),
            },
            "x-bridge-model": query.model,
            "x-bridge-role": query.role,
            "x-bridge-risk-tags": list(query.risk_tags),
        }
    }


def _command_operation(command: BridgeCommandSpec, request_schema: str, response_schema: str) -> dict[str, Any]:
    parameters: list[dict[str, Any]] = []
    if command.idempotent:
        parameters.append(
            {
                "in": "header",
                "name": "Idempotency-Key",
                "required": command.require_idempotency_key,
                "schema": {"type": "string"},
            }
        )
    if command.csrf_required:
        parameters.append({"in": "header", "name": "X-Bridge-CSRF", "required": False, "schema": {"type": "string"}})
    return {
        "post": {
            "summary": command.notes or f"Command {command.name}",
            "tags": list(command.tags or ("commands",)),
            "parameters": parameters,
            "requestBody": _request_body(request_schema),
            "responses": {
                "200": _response("Successful command", response_schema),
                "400": _response("Bad request", "EnvelopeError"),
                "403": _response("Forbidden", "EnvelopeError"),
            },
            "x-bridge-model": command.model,
            "x-bridge-method": command.method,
            "x-bridge-role": command.role,
            "x-bridge-risk-tags": list(command.risk_tags),
        }
    }


def _function_operation(function: BridgeFunctionSpec, request_schema: str, response_schema: str) -> dict[str, Any]:
    return {
        "post": {
            "summary": function.notes or f"Function {function.name}",
            "tags": list(function.tags or ("functions",)),
            "requestBody": _request_body(request_schema),
            "responses": {
                "200": _response("Successful function", response_schema),
                "400": _response("Bad request", "EnvelopeError"),
                "403": _response("Forbidden", "EnvelopeError"),
            },
            "x-bridge-handler": function.handler,
            "x-bridge-role": function.role,
            "x-bridge-idempotent": function.idempotent,
        }
    }


def _request_body(schema_name: str) -> dict[str, Any]:
    return {
        "required": False,
        "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{schema_name}"}}},
    }


def _context_schema(keys: tuple[str, ...]) -> dict[str, Any]:
    return {
        "type": "object",
        "properties": {key: {"type": ["string", "number", "boolean", "array", "object", "null"]} for key in keys},
        "additionalProperties": False,
    }


def _event_headers_schema(headers: tuple[str, ...]) -> dict[str, Any]:
    out: dict[str, Any] = {
        "type": "object",
        "properties": {header: {"type": "string"} for header in headers},
        "additionalProperties": True,
    }
    if headers:
        out["required"] = list(headers)
    return out


def _guess_field_schema(name: str) -> dict[str, Any]:
    lower = name.lower()
    if lower == "id" or lower.endswith("_id"):
        return {"type": "integer"}
    if lower.startswith("is_") or lower.startswith("has_") or lower in {"active", "approved", "archived"}:
        return {"type": "boolean"}
    if lower.endswith("date") and "datetime" not in lower:
        return {"type": "string", "format": "date"}
    if lower.endswith("datetime") or lower.endswith("at"):
        return {"type": "string", "format": "date-time"}
    if any(token in lower for token in ("amount", "price", "cost", "total")):
        return {"type": "number"}
    if any(token in lower for token in ("qty", "quantity", "count", "sequence", "level")):
        return {"type": "integer"}
    return {"type": "string"}


__all__ = [
    "build_asyncapi_document",
    "build_openapi_document",
    "json_schema_for_type",
    "schema_for_params",
]
