"""Canonical neutral report-template builder helpers."""

from .report_template_builder import (
    REPORT_TEMPLATE_BUILDER_SCHEMA_VERSION,
    PreviewToolbarSpec,
    ReportTemplateBandSpec,
    ReportTemplateBuildPlan,
    ReportTemplatePublicationSpec,
    ReportTemplateSourceSpec,
    ReservedPdfLayoutSpec,
    TemplateRegistryEntry,
    TermsDocumentSpec,
    build_design_record_specs,
    build_qweb_template_specs,
    build_report_action_specs,
    build_report_qweb_arch,
    build_report_template_plan,
    build_reserved_pdf_layout_arch,
    build_reserved_pdf_layout_template_spec,
    render_preview_toolbar,
    render_template_registry,
    render_terms_html,
)

__all__ = [
    "REPORT_TEMPLATE_BUILDER_SCHEMA_VERSION",
    "PreviewToolbarSpec",
    "ReportTemplateBandSpec",
    "ReportTemplateBuildPlan",
    "ReportTemplatePublicationSpec",
    "ReportTemplateSourceSpec",
    "ReservedPdfLayoutSpec",
    "TemplateRegistryEntry",
    "TermsDocumentSpec",
    "build_design_record_specs",
    "build_qweb_template_specs",
    "build_report_action_specs",
    "build_report_qweb_arch",
    "build_report_template_plan",
    "build_reserved_pdf_layout_arch",
    "build_reserved_pdf_layout_template_spec",
    "render_preview_toolbar",
    "render_template_registry",
    "render_terms_html",
]
