"""Canonical report-template designer helpers."""

from .report_template_designer import (
    JRXML_NAMESPACE,
    REPORT_DESIGNER_FIELDS,
    REPORT_DESIGNER_MODELS,
    REPORT_DESIGNER_SCHEMA_VERSION,
    REPORT_DESIGNER_VIEW_BLUEPRINTS,
    REPORT_TEMPLATE_RENDER_STAGE_OPTIONS,
    REPORT_TEMPLATE_SOURCE_FORMAT_OPTIONS,
    ReportDesignerFieldSpec,
    ReportDesignerModelSpec,
    ReportDesignerViewBlueprint,
    build_design_record_values,
    build_preview_html,
    dumps_canonical_json,
    flatten_xml_sample,
    flatten_xml_sample_file,
    parse_jrxml_document,
    parse_jrxml_file,
    summarize_design_blueprint,
)

__all__ = [
    "JRXML_NAMESPACE",
    "REPORT_DESIGNER_FIELDS",
    "REPORT_DESIGNER_MODELS",
    "REPORT_DESIGNER_SCHEMA_VERSION",
    "REPORT_DESIGNER_VIEW_BLUEPRINTS",
    "REPORT_TEMPLATE_RENDER_STAGE_OPTIONS",
    "REPORT_TEMPLATE_SOURCE_FORMAT_OPTIONS",
    "ReportDesignerFieldSpec",
    "ReportDesignerModelSpec",
    "ReportDesignerViewBlueprint",
    "build_design_record_values",
    "build_preview_html",
    "dumps_canonical_json",
    "flatten_xml_sample",
    "flatten_xml_sample_file",
    "parse_jrxml_document",
    "parse_jrxml_file",
    "summarize_design_blueprint",
]
